# deploy.yml
- hosts: all
  tasks:
    - name: Copy deploy.sh to remote machine
      copy:
        src: ./deploy.sh
        dest: /tmp/deploy.sh
        mode: '0755'

    - name: Deploy application
      shell: "/tmp/deploy.sh '{{ item }}'"
      loop:
        - your_app_name
